package br.edu.ifpb.aps.jifesp.entity;

public enum NomeModalidade {
    FUTSAL_ADULTO,
    FUTSAL_INTEGRADO,
    TENIS_DE_MESA_MASCULINO,
    TENIS_DE_MESA_FEMININO,
    VOLEIBOL_MASCULINO,
    VOLEIBOL_FEMININO,
    XADREZ_MASCULINO,
    XADREZ_FEMININO
}
